import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("api", {
  getProjects: () => ipcRenderer.invoke("get-projects"),
  addProject: (payload: any) => ipcRenderer.invoke("add-project", payload),
  scanJava: () => ipcRenderer.invoke("scan-java"),
  scanTomcat: () => ipcRenderer.invoke("scan-tomcat"),
  getAppUrl: (name: string) => ipcRenderer.invoke("get-app-url", name),
  getLogsInfo: (name: string) => ipcRenderer.invoke("get-logs-info", name),
  getConfig: (name: string) => ipcRenderer.invoke("get-config", name),
  saveConfig: (payload: any) => ipcRenderer.invoke("save-config", payload),
  start: (name: string) => ipcRenderer.send("start", name),
  debug: (name: string) => ipcRenderer.send("debug", name),
  stop: (name: string) => ipcRenderer.send("stop", name),
  openVscode: (name: string) => ipcRenderer.send("open-vscode", name),
  openUrl: (url: string) => ipcRenderer.send("open-url", url),
  openLog: (payload: any) => ipcRenderer.send("log-open", payload),
  closeLog: () => ipcRenderer.send("log-close"),
  clear: () => ipcRenderer.send("clear-console"),
  onConsole: (cb: (text: string) => void) => ipcRenderer.on("console", (_e, text) => cb(text)),
  onStatus: (cb: (text: string) => void) => ipcRenderer.on("status", (_e, text) => cb(text)),
  onClear: (cb: () => void) => ipcRenderer.on("clear", () => cb()),
  onRunning: (cb: (state: boolean) => void) => ipcRenderer.on("running", (_e, state) => cb(state)),
  onLogChunk: (cb: (text: string) => void) => ipcRenderer.on("log-chunk", (_e, text) => cb(text)),
  windowMinimize: () => ipcRenderer.send("window-minimize"),
  windowToggleMaximize: () => ipcRenderer.send("window-toggle-maximize"),
  windowClose: () => ipcRenderer.send("window-close"),
  onWindowMaximized: (cb: (state: boolean) => void) => ipcRenderer.on("window-maximized", (_e, state) => cb(state)),
  getResourcesPath: () => ipcRenderer.invoke("get-resources-path"),
  chooseResourcesPath: () => ipcRenderer.invoke("choose-resources-path"),
  browsePath: (currentPath: string) => ipcRenderer.invoke("browse-path", currentPath),
  browseFile: (opts: any) => ipcRenderer.invoke("browse-file", opts),
  discoverTests: (name: string) => ipcRenderer.invoke("discover-tests", name),
  runTests: (payload: { name: string; ids: string[]; all?: boolean }) => ipcRenderer.invoke("run-tests", payload),
  stopTests: () => ipcRenderer.send("stop-tests"),
  setTestDir: (payload: { name: string; dir: string }) => ipcRenderer.invoke("set-test-dir", payload),
  onTestProgress: (cb: (payload: any) => void) => ipcRenderer.on("test-progress", (_e, text) => {
    try { cb(JSON.parse(text as string)); } catch (e) { cb({ type: "error", error: String(text) }); }
  }),
  onSettingsUpdated: (cb: () => void) => ipcRenderer.on("settings-updated", () => cb()),
  onShortcut: (cb: (action: string) => void) => ipcRenderer.on("shortcut", (_e, action) => cb(action)),
});
